version: '2'
services:
  remote-stack:
    build: .
    container_name: coffeekraken-remote-stack
    command: bash -c "./start.sh"
    ports:
     - "3030:3030"
     - "8282:8282"
    volumes:
     - .:/code
     - ~/.ssh:/root/.ssh
